### ISSUE TITLE
Create a Flowchart

### ISSUE THREAD

**Issue by reidtevonian** [SIU-CS/Flowchart-Creator-production#13]
**Description**

As a user, I want to be able to create a flowchart, so that I can map out my ideas.

**Acceptance Criteria**

~~-Create a new flowchart can be done with a button or the ctrl-n keyboard shortcut~~ Added to    #43
-Should not be able to create a chart with exact same name as an existing one

**Priority**

Must have

**Time**

Two weeks

**Comment by reidtevonian** [comment]
**Description**

As a user, I want to be able to create a flowchart, so that I can map out my ideas.

**Acceptance Criteria**

Create a new flowchart can be done with a button or the ctrl-n keyboard shortcut
Should not be able to create a chart with exact same name as an existing one
**Priority**

Must have

**Time**

Two weeks

**Comment by regexpressyourself** [comment]
Added with #46
