### ISSUE TITLE
Delete existing flowcharts

### ISSUE THREAD

**Issue by Mikey1848** [SIU-CS/Flowchart-Creator-production#6]
## Description
   As a user, I want to be able to delete my flowcharts.
## Acceptance Criteria
   - Users can delete only their flowcharts from their account when logged in.
   - User should be prompted with a confirmation window when deleting flowcharts.
   - Should be a delete button on the page when they view their flowchart.

## Priority
  Must have
## Time
1 day

**Comment by taylorflatt** [comment]
Note: This relies on the parser saving it to file. So the parser needs to be completed and error tested prior to the ability to delete from disk. I implemented the delete function for the database already. But waiting on the parser to be error tested and finished up. @Mikey1848

**Comment by taylorflatt** [comment]
@regexpressyourself 

https://www.youtube.com/watch?v=4zLfCnGVeL4

**Comment by Mikey1848** [comment]
Sorry for not replying. I am currently working on error testing and finishing up the parser. If I run into any issues I'll be sure to let you know!
